export interface CompanyCatalogItem {
  symbol: string;
  name: string;
  exchange: string;
  country: string;
  sector: string;
  industry: string;
  sources: string[];
}

export const TOP_80_COMPANIES: CompanyCatalogItem[] = [
  // ==========================================
  // 🇮🇳 TOP 40+ INDIAN COMPANIES (NSE / BSE)
  // ==========================================
  {
    symbol: 'RELIANCE',
    name: 'Reliance Industries Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Energy & Conglomerate',
    industry: 'Oil, Gas & Retail & Telecom',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'TCS',
    name: 'Tata Consultancy Services Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Technology',
    industry: 'IT Services & Consulting',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Financial Services',
    industry: 'Private Banking',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'INFY',
    name: 'Infosys Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Technology',
    industry: 'IT Services & Consulting',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'ICICIBANK',
    name: 'ICICI Bank Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Financial Services',
    industry: 'Private Banking',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'BHARTIARTL',
    name: 'Bharti Airtel Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Telecommunications',
    industry: 'Telecom Services',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'SBIN',
    name: 'State Bank of India',
    exchange: 'NSE',
    country: 'India',
    sector: 'Financial Services',
    industry: 'Public Sector Banking',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'ITC',
    name: 'ITC Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Consumer Goods',
    industry: 'FMCG & Hotels',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'HINDUNILVR',
    name: 'Hindustan Unilever Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Consumer Goods',
    industry: 'FMCG & Personal Care',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'LT',
    name: 'Larsen & Toubro Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Industrials',
    industry: 'Engineering & Construction',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'BAJFINANCE',
    name: 'Bajaj Finance Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Financial Services',
    industry: 'Non-Banking Financial Services',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'MARUTI',
    name: 'Maruti Suzuki India Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Automotive',
    industry: 'Passenger Vehicles',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'HCLTECH',
    name: 'HCL Technologies Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Technology',
    industry: 'IT Services & Cloud',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'SUNPHARMA',
    name: 'Sun Pharmaceutical Industries Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Healthcare',
    industry: 'Pharmaceuticals',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'TATAMOTORS',
    name: 'Tata Motors Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Automotive',
    industry: 'Automobile Manufacturing',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'KOTAKBANK',
    name: 'Kotak Mahindra Bank Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Financial Services',
    industry: 'Private Banking',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'AXISBANK',
    name: 'Axis Bank Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Financial Services',
    industry: 'Private Banking',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'TITAN',
    name: 'Titan Company Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Consumer Goods',
    industry: 'Jewelry & Watches',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'ADANIENT',
    name: 'Adani Enterprises Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Energy & Infrastructure',
    industry: 'Trading & Infrastructure',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'NTPC',
    name: 'NTPC Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Utilities',
    industry: 'Power Generation',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'ONGC',
    name: 'Oil & Natural Gas Corp Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Energy',
    industry: 'Oil & Gas Exploration',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'POWERGRID',
    name: 'Power Grid Corp of India Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Utilities',
    industry: 'Power Transmission',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'TATASTEEL',
    name: 'Tata Steel Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Basic Materials',
    industry: 'Steel Manufacturing',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'WIPRO',
    name: 'Wipro Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Technology',
    industry: 'IT Services',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'COALINDIA',
    name: 'Coal India Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Energy & Mining',
    industry: 'Coal Mining',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'BAJAJFINSV',
    name: 'Bajaj Finserv Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Financial Services',
    industry: 'Insurance & Financing',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'M&M',
    name: 'Mahindra & Mahindra Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Automotive',
    industry: 'Farm & Utility Vehicles',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'ASIANPAINT',
    name: 'Asian Paints Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Consumer Goods',
    industry: 'Paints & Coatings',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'ULTRACEMCO',
    name: 'UltraTech Cement Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Basic Materials',
    industry: 'Cement & Building Materials',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'NESTLEIND',
    name: 'Nestle India Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Consumer Goods',
    industry: 'Packaged Foods',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'GRASIM',
    name: 'Grasim Industries Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Basic Materials',
    industry: 'Textiles & Chemicals',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'JSWSTEEL',
    name: 'JSW Steel Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Basic Materials',
    industry: 'Steel & Alloys',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'TECHM',
    name: 'Tech Mahindra Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Technology',
    industry: 'Telecom IT & Software',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'HDFCLIFE',
    name: 'HDFC Life Insurance Co Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Financial Services',
    industry: 'Life Insurance',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'SBILIFE',
    name: 'SBI Life Insurance Co Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Financial Services',
    industry: 'Life Insurance',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'BRITANNIA',
    name: 'Britannia Industries Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Consumer Goods',
    industry: 'Bakery & Dairy Products',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'CIPLA',
    name: 'Cipla Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Healthcare',
    industry: 'Pharmaceuticals & Generics',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'DRREDDY',
    name: 'Dr. Reddy\'s Laboratories Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Healthcare',
    industry: 'Pharmaceuticals',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'EICHERMOT',
    name: 'Eicher Motors Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Automotive',
    industry: 'Motorcycles & Commercial Vehicles',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'TRENT',
    name: 'Trent Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Consumer Goods',
    industry: 'Retail & Fashion (Westside/Zudio)',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'ZOMATO',
    name: 'Zomato Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Technology & Consumer',
    industry: 'Food Delivery & Quick Commerce (Blinkit)',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'POLYCAB',
    name: 'Polycab India Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Industrials',
    industry: 'Wires, Cables & Fast Moving Electrical Goods',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'OLAELEC',
    name: 'Ola Electric Mobility Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Electric Vehicles',
    industry: 'Electric Vehicles & Clean Mobility Tech',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'ADANIPORTS',
    name: 'Adani Ports & Special Economic Zone Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Energy & Infrastructure',
    industry: 'Ports & Logistics',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'ADANIGREEN',
    name: 'Adani Green Energy Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Energy & Infrastructure',
    industry: 'Renewable Solar & Wind Energy',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'ADANIPOWER',
    name: 'Adani Power Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Energy & Infrastructure',
    industry: 'Power Generation & Utilities',
    sources: ['screener-in', 'yahoo-finance'],
  },
  {
    symbol: 'TATACONSUM',
    name: 'Tata Consumer Products Ltd',
    exchange: 'NSE',
    country: 'India',
    sector: 'Consumer Goods',
    industry: 'FMCG, Tea, Coffee & Beverages',
    sources: ['screener-in', 'yahoo-finance'],
  },
];
